#ifndef __OSD_2k_COMMON__H__
#define __OSD_2k_COMMON__H__
#include "number_0_2k.h"
#include "number_1_2k.h"
#include "number_2_2k.h"
#include "number_3_2k.h"
#include "number_4_2k.h"
#include "number_5_2k.h"
#include "number_6_2k.h"
#include "number_7_2k.h"
#include "number_8_2k.h"
#include "number_9_2k.h"
#include "slash_2k.h"
#include "colon_2k.h"
#include "log_2k.h"
#endif /*__OSD_2k_COMMON__H__*/
